package com.space.core.network.service.response

// TODO rename to SPResponseGeneralErrorType
enum class SPResponseStatusCode(override val value: String) : SPResponseBaseErrorType {

    httpSuccess("200"),
    INVALID_DATA("400"),
    httpUnauthorized("401"),
    SocketTimeout("408"),
    INTERNAL_SERVER_ERROR("500"),
    SERVER_UNAVAILABLE("503"),
    GatewayTimeout("504"),
    LoanApplicationInProgress("1239"),
    RejectionInPastThirtyDays("1237"),
    LoanApplicationFail("1240"),
    DisburseUnderProcessing ("1248"),
    RequestTimeout("9"),
    AuthenticationCodeRequired("26004"),
    UntrustedDeviceLivenessCheckRequired("30330"),
    UntrustedDeviceLivenessCheckSuccess("30331"),
    UntrustedDeviceLivenessCheckFailed("30332"),
    MissingAuthenticationCategories("26000"),
    UnknownError("999"),
    SuccessResponseInitialException("9999"),

    error("-1"),
    success("1"),
    Warning("2"),
    updateRequired("3"),
    SecretWordChangeLimit("4"),
    UserNotFound("1000"),
    UserAlreadyExists("1001"),
    PersonalNumberAlreadyExists("1002"),
    InvalidPersonalInfo("1003"),
    InvalidUserNameOrPassword("1004"),
    InactiveDocument("1005"),
    VisualIdentificationFailed("1006"),
    CustomerIsNotVerified("1007"),
    UserTemporarilyBlocked("1008"),
    CustomerNotFound("1009"),
    CustomerAlreadyExists("1010"),
    AccountNotFound("2000"),
    LimitLowerBound("1020"),
    LimitUpperBound("1021"),
    CustomerNotFoundNiBBD("1071"),
    ReferrerUserNotFound("1081"),
    PreferenceKeyNotFound("1085"),
    PasswordChangeRequired("1533"),
    AlertPasswordResetThirdParty("1534"),

    LoanNotFound("1023"),
    LoanNotApproved("1024"),
    LoanApplicationNeedsManualReview("1236"),
    IsInsider("1025"),
    ClientAge("1026"),
    DoubleCitizenship("1027"),
    OtherCitizenship("1028"),
    HasIncassoOrSequestration("1029"),
    SuspiciousIdCard("1032"),
    NotAcceptedBankRequirements("1033"),
    NotFoundInCRABase("1035"),
    ActiveCreditInTBC("1036"),
    DocumentExpired("1047"),
    InstallmentQRCodeUsed("1500"),
    ExistingDocumentExpires("1057"),
    ExistingDocumentExpired("1058"),
    UserAutomaticallyBlocked("1072"),
    UserPermanentBlockWarning("1073"),
    CRANotWorking("1083"),
    CreateUpdateTibcoNotWorking("1084"),
    SourceAccountNotFound("2001"),
    DestinationAccountNotFound("2002"),
    AccountAlreadyExists("2003"),
    GoalNotFound("3000"),

    GoalAlreadyExists("3001"),
    ServiceNotFound("4000"),
    ContractNotFound("5000"),
    CardNotFound("6000"),
    OneTimePasswordServiceBlocked("7000"),
    OneTimePasswordExpired("7001"),
    InvalidOneTimePassword("7002"),
    OTPUserBlockTemporally("5003"),
    OTPUserBlockPermanently("5004"),
    AccountRestricted("7006"),

    NumberChangeOTPExpired("5001"),
    NumberChangeInvalidOTP("5002"),
    NumberChangeAttemptsCountExceeded("30100"),
    LoggedOutPhoneNumberChangeCustomerCheckAttemptsCountExceeded("30102"),

    EndOfDayInProgress("8000"),
    GeneralLedgerAccountNotFound("9000"),
    CustomerEntrepreneurialStatus("1011"),
    AML("1012"),
    GovRestriction("1013"),
    DualCitizenshipOrGreenCard("1014"),
    CustomerIsNotAnAdult("1015"),
    NotCitizen("1016"),
    UserBlocked("1017"),
    InsufficientFunds("1018"),
    NegativePrincipal("1019"),
    LimitExceeded("1020"),
    WithdrawalAmountLimitExceeded("1021"),
    WithdrawalFrequencyLimitExceeded("1022"),
    CardAlreadyExists("4001"),
    TransferNotFound("7000"),
    TransferIsAlreadyCompleted("7001"),
    TransferIsAlreadyBeingReceived("7002"),
    TransferFavoriteNotFound("7003"),
    TransferFavoriteAlreadyExists("7004"),
    PrintJobStatusPrinting("119"),
    VerificationCodeIsIncorrect("0"),
    VerificationCodeIsIncorrectTenTimes("4022"),
    LoanRepaymentIsPossibleNextDay("9035"),
    LoanRepaymentIsPossibleVerySoon("9036"),
    ExistingDocumentExpiredTransfer("1059"),
    ExistingDocumentExpiredProduct("1060"),
    UserPhoneNumberChangeSameNumber("1069"),
    ExistingDocumentInactiveTransfer("1076"),
    ExistingDocumentInactiveProduct("1077"),
    RestrictInternationalPassportPass("1078"),
    UserPasswordChanged("1086"),
    IdentomatGeneralError("1087"),
    IdentomatLimitError("1088"),
    PhoneNumberSkipCountExpired("1090"),
    UserSecretWordSameWithPrevious("1521"),
    IncorrectCardCredentials("4018"),
    PhoneNumberChangeTibcoCheckFailed("30214"),
    PhoneNumberChangeCustomerFoundInTibco("30215"),
    MoneyTransferIsNotAvailable("30240"),
    MoneyTransferAlreadyReceived("30242"),
    MoneyTransferIsInProgress("30243"),
    MoneyTransferIsNotAvailableForNonResident("30247"),
    PassportCheckLimitExceeded("37000"),
    EnteredInvalidDocument("37001"),
    StatementIsNotAvailable("30001"),

    ReferralGeneralError("60001"),
    ReferralUserNotFound("60002"),
    ReferralReferrerUserNotFound("60003"),
    ReferralUserSetOwnReferralCode("60004"),
    ReferralCantSetReferralCodeBecauseLoanTime("60005"),
    ReferralUserTryToSetSameReferralCode("60006"),
    ReferralCantSetReferralCodeBecauseActiveLoanTime("60007"),
    NewCustomerTimeout("61003"),

    LoyaltyRewardConfirmationVerification("10019"),

    ScaCodeRequired("26009"),

    GeneralHttpException("99999");

    companion object {
        fun fromValue(id: String): SPResponseStatusCode {
            for (type in entries) {
                if (type.value == id) {
                    return type
                }
            }
            return UnknownError
        }
    }
}
